### ISSUE TITLE
Can't flash with Arduino

### ISSUE THREAD

**Issue by exp0nge** [Infineon/3D-Magnetic-Sensor-2GO#6]
When I try to flash with Arduino I get this:
`[Error] Infineon.DebuggerExceptions: It seems that JLink software is not installed please download from www.segger.com and install it. You can specify it by setting java property xmcFlasher.JLink.dllPath `

I have tried the GUI and it detects everything normally. I have the board set to XMC1100 XMC2Go, Programmer AVRISP mkll

**Comment by mhollfelder** [comment]
Could you please provide us some more background information on your system?

- What OS and which version are you running?
- What Arduino version do you have?
- What version of J-Link do you have?
- Did you install everything in the standard paths?

The problem is related to not finding the DLL for the J-Link debug probe which is needed to execute the flashing. It is a shared library which the XMC Flasher uses for flashing.

Best regards,

Manuel

**Comment by exp0nge** [comment]
I reinstalled JLink to `C:` instead of my other location and it flashed.
